config/routes.rb
Pghdatahub::Application.routes.draw do
  resources :orgs
  resources :data_sets
  resources :posts
  resources :profiles, :only => [:dashboard]  
    
  devise_for :users, :path_names => {:sign_in => "login", :sign_out => "logout"}, :path => "d"
  
  namespace :admin do
    match '/' => 'users#index'
    resources :users
  end
  
  match '/profiles/dashboard' => 'profiles#dashboard', :as => :user_root

  match '/' => 'search#home'
  match '/search' => 'search#search'
end

app/models/data_set.rb
class DataSet < ActiveRecord::Base
  attr_accessible :name

  def self.types
  	return ['xls', 'kmz', 'zip', 'txt', 'pdf']
  end
end

app/controllers/data_sets_controller.rb
class DataSetsController < ApplicationController
  # GET /data_sets
  # GET /data_sets.json
  def index
    @data_sets = DataSet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @data_sets }
    end
  end

  # GET /data_sets/1
  # GET /data_sets/1.json
  def show
    @data_set = DataSet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @data_set }
    end
  end

  # GET /data_sets/new
  # GET /data_sets/new.json
  def new
    @data_set = DataSet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @data_set }
    end
  end

  # GET /data_sets/1/edit
  def edit
    @data_set = DataSet.find(params[:id])
  end

  # POST /data_sets
  # POST /data_sets.json
  def create
    @data_set = DataSet.new(params[:data_set])

    respond_to do |format|
      if @data_set.save
        format.html { redirect_to @data_set, notice: 'Data set was successfully created.' }
        format.json { render json: @data_set, status: :created, location: @data_set }
      else
        format.html { render action: "new" }
        format.json { render json: @data_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /data_sets/1
  # PUT /data_sets/1.json
  def update
    @data_set = DataSet.find(params[:id])

    respond_to do |format|
      if @data_set.update_attributes(params[:data_set])
        format.html { redirect_to @data_set, notice: 'Data set was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @data_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data_sets/1
  # DELETE /data_sets/1.json
  def destroy
    @data_set = DataSet.find(params[:id])
    @data_set.destroy

    respond_to do |format|
      format.html { redirect_to data_sets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/data_sets_helper.rb
module DataSetsHelper
end

app/views/data_sets/_form.html.erb
<%= form_for(@data_set) do |f| %>
  <% if @data_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@data_set.errors.count, "error") %> prohibited this data_set from being saved:</h2>

      <ul>
      <% @data_set.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/data_sets/_item.html.haml
.row.ds_item
	.span5
		%h2= item['doc_title']
		%h3
			via
			%u= item['doc_dept']
		.row
			.span5
				Juristiction:
				= item['juris']
		.row
			.span5
				406
				downloads
		.row
			.span5
				Created:
				= item['created_date'] || 'Unknown'
		- #Data columns

	.span2
		%h2 Download:
		-# for DataSet.types.each do |t|
			-# @dl = @item.send(t)
			-# if @dl
				- #link_to(image_tag(t + '.png'), dl)
		.row
			.span2
				%a.dl_link{:href => item['doc_reference']}
					%i{:class => "icon-download", :style=>'font-size: 4em'}

app/views/data_sets/edit.html.erb
<h1>Editing data_set</h1>

<%= render 'form' %>

<%= link_to 'Show', @data_set %> |
<%= link_to 'Back', data_sets_path %>

app/views/data_sets/index.html.erb
<h1>Listing data_sets</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @data_sets.each do |data_set| %>
  <tr>
    <td><%= data_set.name %></td>
    <td><%= link_to 'Show', data_set %></td>
    <td><%= link_to 'Edit', edit_data_set_path(data_set) %></td>
    <td><%= link_to 'Destroy', data_set, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Data set', new_data_set_path %>

app/views/data_sets/new.html.erb
<h1>New data_set</h1>

<%= render 'form' %>

<%= link_to 'Back', data_sets_path %>

app/views/data_sets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @data_set.name %>
</p>


<%= link_to 'Edit', edit_data_set_path(@data_set) %> |
<%= link_to 'Back', data_sets_path %>