config/routes.rb
Pghdatahub::Application.routes.draw do
  resources :orgs
  resources :data_sets
  resources :posts
  resources :profiles, :only => [:dashboard]  
    
  devise_for :users, :path_names => {:sign_in => "login", :sign_out => "logout"}, :path => "d"
  
  namespace :admin do
    match '/' => 'users#index'
    resources :users
  end
  
  match '/profiles/dashboard' => 'profiles#dashboard', :as => :user_root

  match '/' => 'search#home'
  match '/search' => 'search#search'
end

app/views/layouts/admin.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Pghdatahub"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") Pghdatahub
          .container.nav-collapse
            %ul.nav
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"
          - flash.each do |name, msg|
            = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

          - if user_signed_in?
            = #link_to "My Profile", user_root_path
            = link_to('Logout', destroy_user_session_path, :method=>'delete')

    .container

      .row
        .span9
          = bootstrap_flash
          = yield
        .span3
          .well.sidebar-nav
            %h3 Sidebar
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"
    
      %footer
        %p &copy; Company 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Right to Know Pittsburgh"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")

  %body
    .container
      .row
        .span10.offset1
          = bootstrap_flash
          - flash.each do |name, msg|
            = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

          %div{:style=>'float:right;margin-right:20px;background-color:#fff;font-size:16px;padding:5px;'}
            = link_to "Home", "/"
            %span{:style=>'color:#ddd;'}
              |
            - if user_signed_in?
              = link_to "My Profile", user_root_path
              %span{:style=>'color:#ddd;'}
                |
              = link_to('Logout', destroy_user_session_path, :method=>'delete')
            - else
              = link_to "Login", new_user_session_path
              %span{:style=>'color:#ddd;'}
                |
              = link_to('Register', new_user_registration_path)

          = yield

          %footer
            %p &copy; Right to Know Pittsburgh 2013 (Creative Commons or some other license?)
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"